# Generated by Django 3.2.6 on 2021-09-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
    ]
