# Generated by Django 3.2.6 on 2021-09-28 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
